version: "3.7"

services:

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-datas:/var/lib/mysql
    env_file: ./.env
    ports:
      - $MYSQL_HOST_PORT:$MYSQL_CONTAINER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: chat
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      
  adminer:
    depends_on:
      - mysql
    image: adminer
    restart: always
    env_file: ./.env
    ports:
      - $ADMINER_HOST_PORT:$ADMINER_CONTAINER_PORT

  chat-api:
    depends_on:
      - mysql
    build:
      context: .
      target: dev
    restart: always
    volumes:
      - ./:/app
    env_file: ./.env
    ports:
      - $API_HOST_PORT:$API_CONTAINER_PORT
      - $API_DEBUGGING_HOST_PORT:$API_DEBUGGING_CONTAINER_PORT
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DB_NAME: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_HOST_PORT

volumes:
  mysql-datas:
  mysql-test-datas: